#!/bin/sh
# repurposeaswan.sh — Set up an interface as a DHCP WAN + watchdog
# Usage: repurposeaswan.sh <interface>
#
# Runs as a daemon; write PID to /tmp/repurpose_<iface>.pid.
# Watchdog loop (every 15s) checks:
#   1. br0 re-binding (fixes it immediately if detected)
#   2. Interface UP state
#   3. udhcpc still alive
# Exits cleanly when /tmp/repurpose_active is removed or changed.

if [ -z "$1" ]; then
    echo "Usage: $0 <interface>" >&2
    exit 1
fi

TARGET_IFACE="$1"
SCRIPT_PATH="/tmp/udhcpc_${TARGET_IFACE}.script"
STATE_FILE="/tmp/repurpose_active"
PID_FILE="/tmp/repurpose_${TARGET_IFACE}.pid"
UDHCPC_PID="/var/run/udhcpc.${TARGET_IFACE}.pid"
LOG="/tmp/repurpose_${TARGET_IFACE}.log"
WATCHDOG_INTERVAL=15

# ── Write PID + state immediately ─────────────────────────────────────────────
echo $$ > "$PID_FILE"
printf '%s' "$TARGET_IFACE" > "$STATE_FILE"
printf '[%s] repurposeaswan started  iface=%s  pid=%s\n' \
    "$(busybox date)" "$TARGET_IFACE" "$$" > "$LOG"

# ── Create the udhcpc handler (single-quoted heredoc — no expansion) ──────────
busybox cat > "$SCRIPT_PATH" << 'UDHCPC_HANDLER_EOF'
#!/bin/sh
# udhcpc handler — generated by repurposeaswan.sh
case "$1" in
    deconfig)
        ip addr flush dev "$interface" 2>/dev/null
        ;;
    bound|renew)
        ip addr flush dev "$interface" 2>/dev/null
        # $subnet is dotted-decimal (e.g. 255.255.255.0); ip(8) accepts it.
        # Fall back to /24 only when udhcpc leaves $subnet empty.
        ip addr add "$ip/${subnet:-24}" dev "$interface" 2>/dev/null
        if [ -n "$router" ]; then
            ip route del default dev "$interface" 2>/dev/null
            ip route add default via "$router" dev "$interface" 2>/dev/null
            # Persist gateway so the watchdog can restore it if the route is stolen
            printf '%s' "$router" > "/tmp/repurpose_gw_${interface}"
            # Idempotent: delete first, then add, so repeated renewals don't stack rules
            iptables -t nat -D POSTROUTING -o "$interface" -j MASQUERADE 2>/dev/null
            iptables -t nat -A POSTROUTING -o "$interface" -j MASQUERADE 2>/dev/null
        fi
        ;;
esac
exit 0
UDHCPC_HANDLER_EOF
busybox chmod +x "$SCRIPT_PATH"

# ── Helper: true if $TARGET_IFACE is currently enslaved to br0 ────────────────
_in_br0() {
    _M=$(ip link show "$TARGET_IFACE" 2>/dev/null \
        | busybox sed -n 's/.* master \([^ ]*\) .*/\1/p' \
        | busybox tr -d '\r\n')
    [ "$_M" = "br0" ]
}

# ── Helper: remove from br0 if enslaved; log the fix ─────────────────────────
# Returns 0 (success) if a fix was applied, 1 if nothing to do.
_fix_br0() {
    if _in_br0; then
        ip link set "$TARGET_IFACE" nomaster 2>/dev/null
        ip link set "$TARGET_IFACE" up 2>/dev/null
        printf '[%s] FIXED br0 re-enslavement — removed %s from br0 + brought UP\n' \
            "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
        return 0
    fi
    return 1
}

# ── Helper: true if our udhcpc PID is alive ───────────────────────────────────
_udhcpc_alive() {
    if [ -f "$UDHCPC_PID" ]; then
        _UP=$(busybox tr -d '\r\n' < "$UDHCPC_PID" 2>/dev/null)
        [ -n "$_UP" ] && kill -0 "$_UP" 2>/dev/null && return 0
    fi
    # Fallback: process name scan
    busybox ps 2>/dev/null \
        | busybox grep "udhcpc" \
        | busybox grep -q "$TARGET_IFACE"
}

# ── Helper: start (or restart) udhcpc ────────────────────────────────────────
# Kills any existing instance for this interface first so we never end up
# with two udhcpc processes racing each other on the same interface (the old
# behaviour was to start a second one on top of the still-running one).
_start_udhcpc() {
    if [ -f "$UDHCPC_PID" ]; then
        _SU_OLD=$(busybox tr -d '\r\n' < "$UDHCPC_PID" 2>/dev/null)
        [ -n "$_SU_OLD" ] && kill "$_SU_OLD" 2>/dev/null
    fi
    busybox sleep 1   # let it die before we grab the PID file
    busybox udhcpc \
        -i "$TARGET_IFACE" \
        -s "$SCRIPT_PATH" \
        -b \
        -p "$UDHCPC_PID" \
        2>/dev/null
    printf '[%s] udhcpc (re)started for %s\n' \
        "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
}

# ── Helper: force a DHCP rediscover after a carrier/br0 event ────────────────
# Called when the watchdog detects the cable was just plugged in (carrier 0→1)
# or that the vendor daemon re-enslaved the interface to br0 (and we just freed
# it). In both cases udhcpc is likely still alive but stuck in background-retry
# mode with a long inter-attempt gap, so it won't discover on its own for a
# long time. We flush stale addresses and start a fresh instance immediately.
_kick_udhcpc() {
    ip addr flush dev "$TARGET_IFACE" 2>/dev/null
    _start_udhcpc
    printf '[%s] KICK: udhcpc restarted for %s (br0/carrier event)\n' \
        "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
}

# ── Helper: wait for target interface to be ready ────────────────────────────
_wait_for_interface_ready() {
    local max_wait=90 waited=0

    # Stage 1: Wait for the interface to exist in the filesystem
    while [ $waited -lt $max_wait ]; do
        [ -e "/sys/class/net/$TARGET_IFACE" ] && break
        busybox sleep 1
        waited=$((waited + 1))
    done

    # Stage 2: Wait for monitord (vendor hardware bring-up finished signal)
    waited=0
    while [ $waited -lt $max_wait ]; do
        busybox pidof monitord >/dev/null 2>&1 && break
        busybox sleep 1
        waited=$((waited + 1))
    done

    # Settle delay
    busybox sleep 3
}

# ── Initial setup ──────────────────────────────────────────────────────────────
printf '[%s] Waiting for interface %s to become ready...\n' \
    "$(busybox date)" "$TARGET_IFACE" >> "$LOG"

_wait_for_interface_ready

printf '[%s] Interface %s ready. Initial setup: nomaster → up → udhcpc\n' \
    "$(busybox date)" "$TARGET_IFACE" >> "$LOG"

ip link set "$TARGET_IFACE" nomaster 2>/dev/null
ip link set "$TARGET_IFACE" up
_start_udhcpc

printf '[%s] Setup complete — watchdog interval=%ds\n' \
    "$(busybox date)" "$WATCHDOG_INTERVAL" >> "$LOG"

# Seed carrier baseline so the watchdog can detect 0→1 transitions.
# Read after initial setup: if cable is already connected at this point
# the watchdog won't fire a spurious kick on the very first tick.
_LAST_CARRIER=$(busybox cat "/sys/class/net/$TARGET_IFACE/carrier" 2>/dev/null | busybox tr -d '\r\n')
_LAST_CARRIER="${_LAST_CARRIER:-0}"

# ── Watchdog loop ──────────────────────────────────────────────────────────────
while true; do
    busybox sleep "$WATCHDOG_INTERVAL"

    # ── Exit condition: state file gone or points to a different iface ────────
    if [ ! -f "$STATE_FILE" ]; then
        printf '[%s] State file removed — exiting\n' \
            "$(busybox date)" >> "$LOG"
        rm -f "$PID_FILE"
        exit 0
    fi
    _CUR=$(busybox tr -d '\r\n' < "$STATE_FILE" 2>/dev/null)
    if [ "$_CUR" != "$TARGET_IFACE" ]; then
        printf '[%s] State changed to "%s" — exiting\n' \
            "$(busybox date)" "$_CUR" >> "$LOG"
        rm -f "$PID_FILE"
        exit 0
    fi

    # ── 1. br0 binding check (highest priority) ───────────────────────────────
    # _fix_br0 returns 0 when it actually had to remove the interface from br0
    # (vendor networking daemon re-enslaved it on link-up — the main reason
    # plugging in a cable after setup failed to obtain an IP).  On that event
    # kick udhcpc immediately; don't wait for the liveness check below, because
    # udhcpc is still alive — just silently stuck in background-retry mode.
    _kicked_this_tick=0
    if _fix_br0; then
        _kick_udhcpc
        _kicked_this_tick=1
    fi

    # ── 2. Interface UP check ─────────────────────────────────────────────────
    _S=$(ip link show "$TARGET_IFACE" 2>/dev/null \
        | busybox grep -o "state [A-Z]*" \
        | busybox awk '{print $2}' \
        | head -1)
    if [ "$_S" != "UP" ]; then
        ip link set "$TARGET_IFACE" up 2>/dev/null
        printf '[%s] Interface %s was %s — brought back UP\n' \
            "$(busybox date)" "$TARGET_IFACE" "${_S:-UNKNOWN}" >> "$LOG"
    fi

    # ── 3. udhcpc liveness check ──────────────────────────────────────────────
    if ! _udhcpc_alive; then
        printf '[%s] udhcpc died — restarting\n' \
            "$(busybox date)" >> "$LOG"
        _start_udhcpc
        _kicked_this_tick=1
    fi

    # ── 4. Default route maintenance ──────────────────────────────────────────
    # If the system (vendor firmware, nas* interface, etc.) steals the default
    # route away from our repurposed WAN, restore it from the saved gw file.
    _GW_FILE="/tmp/repurpose_gw_${TARGET_IFACE}"
    if [ -f "$_GW_FILE" ]; then
        _GW=$(busybox tr -d '\r\n' < "$_GW_FILE" 2>/dev/null)
        if [ -n "$_GW" ]; then
            _CUR=$(ip route show default 2>/dev/null | head -1)
            case "$_CUR" in
                *"dev $TARGET_IFACE"*) ;; # already correct
                *)
                    ip route del default 2>/dev/null
                    ip route add default via "$_GW" dev "$TARGET_IFACE" 2>/dev/null
                    printf '[%s] RESTORED default route via %s dev %s\n' \
                        "$(busybox date)" "$_GW" "$TARGET_IFACE" >> "$LOG"
                    ;;
            esac
        fi
    fi

    # ── 5. Carrier state tracking (cable plug-in detection) ───────────────────
    # Belt-and-suspenders for cases where the vendor daemon does NOT re-enslave
    # the interface to br0 on link-up (rare but possible — e.g. when a WLAN
    # interface associates with an AP, or when the LAN switchd handles link
    # events without touching br0).  A 0→1 carrier transition that wasn't
    # already handled by the br0 fix above means cable just appeared —
    # kick udhcpc so we get a lease right away instead of waiting for its
    # next background-retry interval (which can be several minutes).
    _CUR_CARRIER=$(busybox cat "/sys/class/net/$TARGET_IFACE/carrier" 2>/dev/null \
        | busybox tr -d '\r\n')
    _CUR_CARRIER="${_CUR_CARRIER:-0}"
    if [ "$_CUR_CARRIER" = "1" ] && [ "$_LAST_CARRIER" = "0" ] \
       && [ "$_kicked_this_tick" = "0" ]; then
        printf '[%s] Carrier came up on %s (no br0 event) — kicking udhcpc\n' \
            "$(busybox date)" "$TARGET_IFACE" >> "$LOG"
        ip link set "$TARGET_IFACE" up 2>/dev/null
        _kick_udhcpc
    fi
    _LAST_CARRIER="$_CUR_CARRIER"
done
