#!/bin/sh
# LAN port link speed persistence script.
# Installed at: /lmepisowifi/www2/sh/startup.sh
# Called from:  /etc/init.d rc35
#
# The section between BEGIN_LAN_SPEEDS and END_LAN_SPEEDS is managed
# automatically by lme.cgi whenever a port link speed is applied or
# reverted via the web UI.  Do NOT edit those lines by hand.

# ---------------------------------------------------------------------------
# wait_for_iface <iface>
#   Polls ifconfig every second until <iface> appears, or 60 s timeout.
#   Returns 0 on success, 1 on timeout (and logs via logger).
# ---------------------------------------------------------------------------
wait_for_iface() {
    _WFI_IFACE="$1"
    _WFI_TRIES=0
    while [ "$_WFI_TRIES" -lt 60 ]; do
        if ifconfig "$_WFI_IFACE" >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
        _WFI_TRIES=$((_WFI_TRIES + 1))
    done
    return 1
}

# ---------------------------------------------------------------------------
# LAN port link-speed entries.
# Each line is generated by lme.cgi in the form:
#   ( wait_for_iface <iface> && diag port set auto-nego port <idx> ability <speeds> ) &
#
# Entries run in the background so this script returns immediately.
# Interfaces: LAN 1 = eth0.2 (diag port 0), LAN 2 = eth0.3 (diag port 1)
# ---------------------------------------------------------------------------
# --- BEGIN_LAN_SPEEDS ---
# --- END_LAN_SPEEDS ---

# ---------------------------------------------------------------------------
# Auto-reboot schedule daemon.
# This line is managed automatically by lme.cgi (reboot_sched_set action).
# Do NOT edit by hand.
# ---------------------------------------------------------------------------
# --- BEGIN_REBOOT_SCHED ---
# --- END_REBOOT_SCHED ---

# ---------------------------------------------------------------------------
# WAN repurpose persistence.
# This line is managed automatically by wan-repurpose.cgi (apply / revert).
# Do NOT edit by hand.
# ---------------------------------------------------------------------------
# --- BEGIN_WAN_REPURPOSE ---
( wait_for_iface wlan1-vxd && sh /lmepisowifi/www2/sh/repurposeaswan.sh wlan1-vxd ) &
# --- END_WAN_REPURPOSE ---

# ---------------------------------------------------------------------------
# IP Access Control (ACC_TBL) reapplication.
# iptables rules don't survive a reboot; the mib ACC_TBL values do. This
# rebuilds the telnet/ftp/tftp/web/https/ssh/snmp firewall rules from
# whatever levels are currently persisted in the mib. Managed by
# ipacl.cgi (Admin > IP ACL) — do NOT edit this line by hand.
# ---------------------------------------------------------------------------
# --- BEGIN_IPACL ---
( sh /lmepisowifi/www2/sh/ipacl.sh apply_all ) &
# --- END_IPACL ---

# ---------------------------------------------------------------------------
# OTA scheduled update check.
# One-shot check ~15 min after boot (so a device isn't left waiting up to
# 6h for the first check). The recurring every-6h check is a crond job
# (see /lmepisowifi/startup.sh), not a persistent background loop, since
# crond survives independently of this process and doesn't leak a sleeping
# shell for hours at a time. Behaviour is governed by /lmepisowifi/ota.env
# (OTA_AUTO: 0 = notify only, 1 = auto-apply), toggled from Admin > System >
# Software Update.
# ---------------------------------------------------------------------------
# --- BEGIN_OTA_CHECK ---
( sleep 900; [ -x /lmepisowifi/ota.sh ] && sh /lmepisowifi/ota.sh cron >/dev/null 2>&1 ) &
# --- END_OTA_CHECK ---

# ---------------------------------------------------------------------------
# Band Steering Watchdog.
# libmib.so re-applies the WRONG per-radio stactrl_prefer_band values to the
# driver on every boot / wlan_apply restart (the inverted-preference bug).
# It only starts when WIFI_STA_CONTROL is 1 (5GHz) or 3 (2.4GHz); when steering
# is disabled the monitor process is never spawned. When enabled it waits for
# both radios, corrects the driver state once, then keeps a lightweight monitor
# loop re-checking every 60s so the fix survives any later libmib re-clobber.
# Managed alongside wlanadvanced.cgi — do NOT edit by hand.
# ---------------------------------------------------------------------------
# --- BEGIN_BANDSTEER_WD ---
_BSWD_MODE=$(mib get WIFI_STA_CONTROL | busybox grep "=" | busybox cut -d'=' -f2- | busybox tr -d '\r\n')
if [ "$_BSWD_MODE" = "1" ] || [ "$_BSWD_MODE" = "3" ]; then
    ( wait_for_iface wlan0 && wait_for_iface wlan1 \
        && sh /lmepisowifi/www2/sh/bandsteer_watchdog.sh once \
        && sh /lmepisowifi/www2/sh/bandsteer_watchdog.sh monitor 60 ) &
fi
# --- END_BANDSTEER_WD ---
